merge_queue:
  max_parallel_checks: 1

queue_rules:
  - name: auto-main
    queue_conditions:
      - base = main
      - label = vm4-migrate-auto-a
    merge_conditions:
      - label = vm4-never-merge
    merge_method: merge
    autoqueue: true

  - name: auto-release
    queue_conditions:
      - base = release
      - label = vm4-migrate-auto-b
    merge_conditions:
      - label = vm4-never-merge
    merge_method: merge
    autoqueue: true

  - name: manual-main
    queue_conditions:
      - base = main
      - label = vm4-manual-only
    merge_conditions:
      - label = vm4-never-merge
    merge_method: merge
