name: VM4 standard merge post-success head freshness R3
on:
  pull_request:
permissions:
  contents: read
jobs:
  delay:
    name: VM4 standard merge post-success head freshness R3
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.head_ref, 'mergify/merge-queue/')
        run: sleep 75
      - run: echo old-green
