name: VM4 config generation delay

on:
  pull_request:

permissions:
  contents: read

jobs:
  delay:
    name: VM4 config generation delay
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
      - run: echo VM4_CONFIG_GENERATION_DELAY_PASS
