name: VM4 standard merge fork post-success head R4
on:
  pull_request:
permissions:
  contents: read
jobs:
  delay:
    if: github.event.action != 'synchronize' || github.head_ref != 'vm4-standard-fork-r4-b'
    name: VM4 standard merge fork post-success head R4
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.head_ref, 'mergify/merge-queue/')
        run: sleep 60
      - run: echo old-green
